import type { Metadata } from "next";
import Image from "next/image";
import { ThemeImage } from "@/components/theme-image";
export const metadata: Metadata = { title: "Experiência", description: "Experiência profissional e formação de Victor Castro.", alternates: { canonical: "/experience" } };
const experience = [
  { role: "Data Scientist Specialist", org: "Unimed Federação Centro Brasileira", start: "2025", end: "Presente", logo: "/unimed-logo.png", details: ["Desenvolvimento de pipelines e de um Data Warehouse regional para Goiás e Tocantins.", "Soluções de machine learning, LLM e RAG para apoio à decisão e auditoria médica.", "Aplicações, automações e dashboards com práticas de CI/CD, governança e qualidade de dados."] },
  { role: "Full-Stack Developer", org: "Ágil Serviços", start: "2024", logo: "/logo-agil.jpg", details: ["Interfaces em React e TypeScript integradas a APIs desenvolvidas em Python.", "PostgreSQL, bancos Azure e Redis aplicados a persistência, autenticação e sessões.", "Conteinerização com Docker, pipelines CI/CD, documentação e automações de negócio."] },
  { role: "Bioinformatics Intern", org: "Neurolab · UFG", start: "2023", logo: "/logo-ufg-vertical.png", ufg: true, details: ["Processamento e análise de dados relacionados a doenças neurodegenerativas.", "Trabalho interdisciplinar para transformar resultados técnicos em evidências interpretáveis."] },
  { role: "Bioinformatics Intern", org: "Laboratório de Imunorregulação · UFG", start: "2022", end: "2023", logo: "/logo-ufg-vertical.png", ufg: true, details: ["Desenvolvimento de um modelo in silico de vacina contra Chikungunya.", "Integração de dados biológicos e ferramentas de imunoinformática para seleção de candidatos."] },
  { role: "Bioinformatics Intern", org: "LabMol · UFG", start: "2019", end: "2020", logo: "/logo-ufg-vertical.png", ufg: true, details: ["Pesquisa de inibidores de proteínas do vírus Zika por modelagem molecular e análise de dados.", "Trabalho reconhecido com o 2º lugar em Ciências da Saúde na UFG."] },
] as const;
export default function ExperiencePage() {
  return <><header className="page-header experience-header"><div className="container"><span className="eyebrow">Experiência</span><div className="editorial-heading"><h1 className="page-title">Pesquisa, produto<br/><span>e engenharia.</span></h1><p className="lead">Uma trajetória construída entre equipes multidisciplinares, sistemas em produção e investigação científica.</p></div></div></header><section className="container section">
    <div className="timeline">{experience.map(x => <article className="timeline-item" key={`${x.role}-${x.org}`}><div className="timeline-date"><span>{x.start}</span>{"end" in x && x.end && <><small>até</small><span>{x.end}</span></>}</div><div className="institution-logo">{"ufg" in x && x.ufg ? <ThemeImage darkSrc="/logo-ufg-horizontal.png" lightSrc="/logo-ufg-horizontal-colorida.png" alt={`Logo ${x.org}`} width={120} height={70}/> : <Image src={x.logo} alt={`Logo ${x.org}`} width={100} height={70}/>}</div><div className="timeline-content"><p className="timeline-org">{x.org}</p><h2>{x.role}</h2><ul>{x.details.map(detail => <li key={detail}>{detail}</li>)}</ul></div></article>)}</div>
    <div className="education"><div className="section-head"><div><span className="eyebrow">Formação</span><h2>Base acadêmica.</h2></div></div><div className="education-grid"><article className="education-card"><div className="education-logo"><ThemeImage darkSrc="/logo-ufg-horizontal.png" lightSrc="/logo-ufg-horizontal-colorida.png" alt="Universidade Federal de Goiás" width={160} height={82}/></div><div><span className="meta">2019 a 2023</span><h3>Bacharelado em Biotecnologia</h3><p>Universidade Federal de Goiás</p></div></article><article className="education-card"><div className="education-logo ada"><Image src="/ada-logo.jpg" alt="Ada Tech" width={130} height={130}/></div><div><span className="meta">2024</span><h3>Data Scientist</h3><p>Ada Tech</p></div></article></div></div>
  </section></>;
}
