import type { Metadata } from "next";
import Image from "next/image";
import { RouteHero } from "@/components/route-hero";
import { ThemeImage } from "@/components/theme-image";
import { experiences } from "@/lib/experience";
export const metadata: Metadata = { title: "Experiência", description: "Experiência profissional e formação de Victor Castro.", alternates: { canonical: "/experience" } };
export default function ExperiencePage() {
  return <><RouteHero className="experience-header"><div className="container"><span className="eyebrow">Experiência</span><div className="editorial-heading"><h1 className="page-title">Pesquisa, produto<br/><span>e engenharia.</span></h1><p className="lead">Uma trajetória construída entre equipes multidisciplinares, sistemas em produção e investigação científica.</p></div></div></RouteHero><section className="container section">
    <div className="timeline">{experiences.map(x => <article className="timeline-item" key={`${x.role}-${x.org}`}><div className="timeline-date"><span>{x.start}</span>{x.end && <><small>até</small><span>{x.end}</span></>}</div><div className="institution-logo">{x.ufg ? <ThemeImage darkSrc="/images/institutions/ufg-horizontal-dark.png" lightSrc="/images/institutions/ufg-horizontal-light.png" alt={`Logo ${x.org}`} width={120} height={70}/> : x.logo ? <Image src={x.logo} alt={`Logo ${x.org}`} width={100} height={70}/> : null}</div><div className="timeline-content"><p className="timeline-org">{x.org}</p><h2>{x.role}</h2><ul>{x.details.map(detail => <li key={detail}>{detail}</li>)}</ul></div></article>)}</div>
    <div className="education"><div className="section-head"><div><span className="eyebrow">Formação</span><h2>Base acadêmica.</h2></div></div><div className="education-grid"><article className="education-card"><div className="education-logo"><ThemeImage darkSrc="/images/institutions/ufg-horizontal-dark.png" lightSrc="/images/institutions/ufg-horizontal-light.png" alt="Universidade Federal de Goiás" width={160} height={82}/></div><div><span className="meta">2019 a 2023</span><h3>Bacharelado em Biotecnologia</h3><p>Universidade Federal de Goiás</p></div></article><article className="education-card"><div className="education-logo ada"><Image src="/images/institutions/ada.webp" alt="Ada Tech" width={130} height={130}/></div><div><span className="meta">2024</span><h3>Data Scientist</h3><p>Ada Tech</p></div></article></div></div>
  </section></>;
}
